# Generated by theme/apply-theme.sh — edit theme/colors.sh instead
# ------------------------------
#  Swaylock
# ------------------------------

# Background
image=/home/leberton/bg.jpg
scaling=fill
effect-blur=30x8
effect-vignette=0.25:0.75

# Transparent overlay
color={{sl_bg}}

# Clock
clock
timestr=%I:%M %p
datestr=%A, %d %B %Y
font=JetBrainsMono Nerd Font
font-size=38
time-color={{sl_text}}
date-color={{sl_subtext}}
layout-text-color={{sl_text}}

# Ring
ring-color={{sl_surface}}
inside-color={{sl_inner}}
line-color={{sl_surface}}
separator-color=00000000

ring-width=14
inside-ring-width=0
line-uses-inside

# Indicator
indicator
indicator-radius=130
indicator-thickness=18
indicator-caps-lock

# Key highlights
key-hl-color={{sl_blue}}
bs-hl-color={{sl_red}}

# Caps lock
caps-lock-text-color={{sl_red}}
caps-lock-key-hl-color={{sl_red}}
caps-lock-bs-hl-color={{sl_red}}

# Verification (typing password)
ring-ver-color={{sl_blue}}
inside-ver-color={{sl_inner_active}}
text-ver-color={{sl_blue}}

# Wrong password
ring-wrong-color={{sl_red}}
inside-wrong-color={{sl_inner_active}}
text-wrong-color={{sl_red}}

# Clear state
ring-clear-color={{sl_yellow}}
inside-clear-color={{sl_inner_active}}
text-clear-color={{sl_yellow}}

# Grace period
grace=3
grace-no-mouse
grace-no-touch

# Animations
fade-in=0.4
fade-out=0.25

# Extra
show-failed-attempts
show-keyboard-layout
ignore-empty-password
daemonize
