#!/bin/bash

CONF_DIR="$HOME/.dotfiles/scripts/conf"

case "$1" in
	-a|all)
		shift
		$CONF_DIR/all
		;;
	-s|single)
		shift
		for arg in "$@"; do
			if [ -x "$CONF_DIR/$arg" ]; then
				"$CONF_DIR/$arg"
				exit 0
			fi
		done
		echo -e "${RED} Error: ${NC}No valid script found for: $*${RESET}"
		exit 1
		;;
    *)
        for arg in "$@"; do
            if [ -x "$CONF_DIR/$arg" ]; then
                "$CONF_DIR/$arg"
                exit 0
            fi
        done
        echo -e "${RED} Error: ${NC}No valid script found for: $*${RESET}"
        exit 1
        ;;
esac

