#!/bin/bash

if [ "$(uname)" == "Darwin" ]; then
	$SECHO "${GREEN}→ macOS detected. Skipping Hyprland config...${RESET}"
	exit 1
fi

DOTFILES_DIR=$HOME/.dotfiles
CONFIG_DIR=$HOME/.config
HYPRLAND_CONFIG=$CONFIG_DIR/hypr
HYPRLAND_DOT=$DOTFILES_DIR/hypr

LOGFILE="$DOTFILES_DIR/logs/hyprland.log"
mkdir -p "$(dirname "$LOGFILE")"

if [ -L "$HYPRLAND_CONFIG" ]; then
	$SECHO "${GREEN}✔ Hyprland config is already linked.${RESET}"
	exit 0
fi

if [ -d "$HYPRLAND_CONFIG" ]; then
	$SECHO "${YELLOW}→ Hyprland config is not linked from dotfiles.${RESET}"
	$SECHO "${YELLOW}→ Removing existing config...${RESET}"
	rm -rf "$HYPRLAND_CONFIG"
	$SECHO "${YELLOW}→ Linking hyprland config...${RESET}"
	ln -s "$HYPRLAND_DOT" "$HYPRLAND_CONFIG" >> "$LOGFILE" 2>&1
	exit 0
fi

if [ ! -d "$HYPRLAND_DOT" ]; then
	$SECHO "${RED}✖ ERROR: No hyprland config found in dotfiles.${RESET}"
	exit 1
fi

if [ ! -d "$HYPRLAND_CONFIG" ] && [ -d "$HYPRLAND_DOT" ]; then
	$SECHO "${YELLOW}→ Linking hyprland config...${RESET}"
	ln -s "$HYPRLAND_DOT" "$HYPRLAND_CONFIG" >> "$LOGFILE" 2>&1
	$SECHO "${GREEN}✔ Linking successful.${RESET}"
fi
