#!/bin/zsh

if [ ! -d $DOTFILES ]; then
	$SECHO "${RED}Please set the DOTFILES environment variable to the path of your dotfiles repository.${RESET}"
	exit 1
fi

KITTY_CONF_DIR="$HOME/.config/kitty"
KITTY_DCONF_DIR="$DOTFILES/scripts/conf/kitty"

if [ -d $KITTY_DCONF_DIR ]; then
	$SECHO "${RED}Kitty configuration directory not found: $KITTY_DCONF_DIR${RESET}"
	exit 1
fi

if [ -d $KITTY_CONF_DIR ]; then
	$SECHO "${YELLOW}Kitty configuration directory already exists: $KITTY_CONF_DIR${RESET}"
	$SECHO "${GREEN}Removing existing configuration...${RESET}"
	rm -rf $KITTY_CONF_DIR
	mkdir -p $KITTY_CONF_DIR
	$SECHO "${GREEN}Linking configuration.${RESET}"
	ln -s $KITTY_DCONF_DIR $KITTY_CONF_DIR > /dev/null 2&1
	$SECHO "${GREEN}Kitty configuration linked successfully. Please restart kitty.${RESET}"
fi

if [ ! -d $KITTY_CONF_DIR ]; then
	$SECHO "${YELLOW}Kitty configuration directory not found. Creating it...${RESET}"
	mkdir -p $KITTY_CONF_DIR
	$SECHO "${GREEN}Linking configuration.${RESET}"
	ln -s $KITTY_DCONF_DIR $KITTY_CONF_DIR > /dev/null 2&1
	$SECHO "${GREEN}Kitty configuration linked successfully. Please restart kitty.${RESET}"
fi
