#!/bin/bash

PACKAGE_MANAGER=dnf

GIT_DOTFILES=git@github.com:LeoTrain/.dotfiles.git
DOTFILES_DIR=$HOME/.dotfiles
DOTFILES_CONFIG=$DOTFILES_DIR/nvim
NEOVIM_CONFIG=$HOME/.config/nvim

LOGFILE="neovim.log"

GREEN='\033[0;32m'
RED='\033[0;31m'
YELLOW='\033[1;33m'
RESET='\033[0m'

SLOW_ECHO_SCRIPT="$DOTFILES_DIR/scripts/slow_echo"

link_neovim() {
  echo -e "${YELLOW}"
  $SLOW_ECHO_SCRIPT "→ Linking neovim config..."
  echo -e "${RESET}"

  if [ ! -d "$DOTFILES_CONFIG" ]; then
    echo -e "${RED}"
    $SLOW_ECHO_SCRIPT "✖ ERROR: No neovim config found in dotfiles."
    echo -e "${RESET}"
    return
  fi

  if [ -L "$NEOVIM_CONFIG" ] || [ -d "$NEOVIM_CONFIG" ]; then
    rm -rf "$NEOVIM_CONFIG"
  fi

  mkdir -p "$(dirname "$NEOVIM_CONFIG")"
  if ln -s "$DOTFILES_CONFIG" "$NEOVIM_CONFIG" >> "$LOGFILE" 2>&1; then
    echo -e "${GREEN}"
    $SLOW_ECHO_SCRIPT "✔ Linking successful."
    echo -e "${RESET}"
  else
    echo -e "${RED}"
    $SLOW_ECHO_SCRIPT "✖ ERROR: linking failed."
    echo -e "${RESET}"
  fi
}

# Clear the log
: > "$LOGFILE"

if command -v nvim >> "$LOGFILE" 2>&1; then
	echo -e "${GREEN}"
	$SLOW_ECHO_SCRIPT "✔ Neovim is available."
	echo -e "${RESET}"
	if [ -L "$NEOVIM_CONFIG" ]; then
		echo -e "${GREEN}"
		$SLOW_ECHO_SCRIPT "→ Neovim config is linked from dotfiles."
		echo -e "${RESET}"
	else
		echo -e "${YELLOW}"
		$SLOW_ECHO_SCRIPT "→ Neovim config is not linked from dotfiles."
		echo -e "${RESET}"
		link_neovim
	fi
else
	echo -e "${YELLOW}"
	$SLOW_ECHO_SCRIPT "→ Neovim not found. Checking for Vim..."
	echo -e "${RESET}"
	if command -v vim >> "$LOGFILE" 2>&1; then
		echo -e "${GREEN}"
		$SLOW_ECHO_SCRIPT "✔ Vim is available."
		echo -e "${RESET}"
	else
		echo -e "${YELLOW}"
		$SLOW_ECHO_SCRIPT "→ Vim not found. Checking for package manager..."
		echo -e "${RESET}"
		#link_neovim
	fi
fi
