#!/bin/bash

PACKAGE_MANAGER=dnf

GIT_DOTFILES=git@github.com:LeoTrain/.dotfiles.git
DOTFILES_DIR=$HOME/.dotfiles
DOTFILES_CONFIG=$DOTFILES_DIR/nvim
NEOVIM_CONFIG=$HOME/.config/nvim

LOGFILE="neovim.log"

link_neovim() {
  $SECHO "${YELLOW}→ Linking neovim config...${RESET}"
  if [ ! -d "$DOTFILES_CONFIG" ]; then
    $SECHO "${RED}✖ ERROR: No neovim config found in dotfiles.${RESET}"
    return
  fi

  if [ -L "$NEOVIM_CONFIG" ] || [ -d "$NEOVIM_CONFIG" ]; then
    rm -rf "$NEOVIM_CONFIG"
  fi

  mkdir -p "$(dirname "$NEOVIM_CONFIG")"
  if ln -s "$DOTFILES_CONFIG" "$NEOVIM_CONFIG" >> "$LOGFILE" 2>&1; then
    $SECHO "${GREEN}✔ Linking successful.${RESET}"
  else
    $SECHO "${RED}✖ ERROR: linking failed.${RESET}"
  fi
}

# Clear the log
: > "$LOGFILE"

if command -v nvim >> "$LOGFILE" 2>&1; then
	$SECHO "${GREEN}✔ Neovim is available.${RESET}"
	echo -e "${RESET}"
	if [ -L "$NEOVIM_CONFIG" ]; then
		$SECHO "${GREEN}→ Neovim config is linked from dotfiles.${RESET}"
	else
		$SECHO "${YELLOW}→ Neovim config is not linked from dotfiles.${RESET}"
		link_neovim
	fi
else
	$SECHO "${YELLOW}→ Neovim not found. Checking for Vim...${RESET}"
	if command -v vim >> "$LOGFILE" 2>&1; then
		$SECHO "${GREEN}✔ Vim is available.${RESET}"
	else
		$SECHO "${YELLOW}→ Vim not found. Checking for package manager...${RESET}"
		#link_neovim
	fi
fi
