#!/bin/bash

if [[ "$OSTYPE" == "linux-gnu"* ]]; then
    release_file=/etc/os-release

    if grep -q "Arch" $release_file; then
        sudo pacman -Syu
    elif grep -q "Ubuntu" $release_file; then
        sudo apt update
        sudo apt dist-upgrade
    elif grep -q "Fedora" $release_file; then
        sudo dnf update
    else
        echo "Linux distro not recognized. Please update manually or modify the 'update' script."
    fi

elif [[ "$OSTYPE" == "darwin"* ]]; then
    softwareupdate -i -a
else
    echo "Système non pris en charge : $OSTYPE"
fi
