#!/bin/zsh

ZSH_CONF="$HOME/.zshrc"
ZSH_DOT="$DOTFILES/zshrc/.zshrc"

if [ -f "$ZSH_CONF" ]; then
  $SECHO "${GREEN}✔ Zsh config already exists at ~/.zshrc${RESET}"
  source "$ZSH_CONF"
else
  $SECHO "${YELLOW}→ No Zsh config found, linking from dotfiles...${RESET}"
  if ln -s "$ZSH_DOT" "$ZSH_CONF" >/dev/null 2>&1; then
	  $SECHO "${GREEN}✔ Linking successful.${RESET}"
	  source "$ZSH_CONF"
  else
    $SECHO "${RED}✖ ERROR: Linking failed. See $LOGFILE${RESET}"
  fi
fi

