require("config.colorscheme")

vim.keymap.set('n', '<Esc>', '<cmd>nohlsearch<CR>')
vim.keymap.set('n', '<leader>q', vim.diagnostic.setloclist, { desc = 'Open diagnostic [Q]uickfix list' })
vim.keymap.set('n', '<leader>e', '<cmd>Ex<CR>')
vim.keymap.set('n', '<leader>ff', "<cmd>Telescope find_files<CR>", {})
vim.keymap.set('n', '<leader>fg', "<cmd>Telescope live_grep<CR>", {})
vim.keymap.set('n', '<leader>fw', "<cmd>Telescope grep_string<CR>", {})
vim.keymap.set('n', '<leader>tc', require("config.colorscheme").toggle, { desc = "Toggle theme light/dark" })
vim.keymap.set('n', '<leader>tt', '<cmd>Twilight<CR>', { desc = "Toggle twilight"})
vim.keymap.set('n', '<leader>tz', '<cmd>ZenMode<CR>', { desc = "Toggle twilight"})
