# Generated by theme/apply-theme.sh — edit theme/colors.sh instead

# BACKGROUND
background {
    monitor =
    path = ~/.config/hypr/hypr.png
    blur_passes = 0
    contrast = 0.8916
    brightness = 0.8172
    vibrancy = 0.1696
    vibrancy_darkness = 0.0
}

# GENERAL
general {
    no_fade_in = false
    grace = 0
    disable_loading_bar = false
}

# TIME
label {
    monitor =
    text = cmd[update:1000] echo "<span>$(date +"%I:%M")</span>"
    color = {{hl_text}}
    font_size = 160
    font_family = SF Pro Display Bold
    position = 0, 370
    halign = center
    valign = center
}

# DATE
label {
    monitor =
    text = cmd[update:1000] echo -e "$(date +"%A, %B %d")"
    color = {{hl_text}}
    font_size = 28
    font_family = SF Pro Display Bold
    position = 0, 490
    halign = center
    valign = center
}

# FOREGROUND
image {
    monitor =
    path = ~/.config/hypr/foreground.png
    size = 700
    border_size = 0
    rounding = 0
    rotate = 0
    reload_time = 0
    reload_cmd =
    position = 0, -66
    halign = center
    valign = center
}

# USER
label {
    monitor =
    text =     $USER
    color = {{hl_text2}}
    font_size = 18
    font_family = SF Pro Display Bold
    position = 0, -180
    halign = center
    valign = center
}

# INPUT FIELD
input-field {
    monitor =
    size = 300, 60
    outline_thickness = 2
    dots_size = 0.2
    dots_spacing = 0.2
    dots_center = true
    outer_color = {{hl_outer}}
    inner_color = {{hl_inner}}
    font_color = {{hl_font}}
    fade_on_empty = false
    font_family = SF Pro Display Bold
    placeholder_text = <i><span foreground="##ffffff99">🔒 Enter Pass</span></i>
    hide_input = false
    position = 0, -250
    halign = center
    valign = center
}
