#!/bin/bash

LIB_DIR=$HOME/lab/libft/libft

if [ ! -d $LIB_DIR ]; then
	$SECHO "${RED}Library not found at $LIB_DIR${RESET}"
	exit 1
fi

if ln -s $LIB_DIR "$(pwd)/libft"; then
	$SECHO "${GREEN}✔ Library linked successfully.${RESET}"
else
	$SECHO "${RED}✖ ERROR: linking failed.${RESET}"
fi
