#!/bin/bash

if [[ "$OSTYPE" == "linux-gnu"* ]]; then
	if [ $# -lt 2 ]; then
		echo "Usage Linux: $0 <title> <message> [flags...]"
		exit 1
	fi
	TITLE="$1"
	MESSAGE="$2"
	shift 2
	FLAGS=("$@")
	notify-send "${FLAGS[@]}" "$TITLE" "$MESSAGE"
elif [[ "$OSTYPE" == "darwin"* ]]; then
	if [ $# -lt 2 ]; then
		echo "Usage Mac: $0 <title> <message>"
		exit 1
	fi
	TITLE="$1"
	MESSAGE="$2"
	osascript -e "display notification \"$MESSAGE\" with title \"$TITLE\""
else
	echo "Unsupported OS"
	exit 1
fi
