#!/bin/bash

slow_echo() {
  local text="$1"
  local delay=${2:-0.03}
  text=$(echo -e "$text")
  for ((i=0; i<${#text}; i++)); do
    printf "%s" "${text:i:1}"
    sleep "$delay"
  done
  printf "\n"
}

if [[ $# -ne 1 ]]; then
  echo "Usage: slow_echo <text>"
  exit 1
fi

slow_echo "$1"
