#!/bin/bash

# Check arguments
SRC_FOLDER=$1
REMOTE_URL=$2

if [ -z "$SRC_FOLDER" ] || [ -z "$REMOTE_URL" ]; then
	$SECHO "${RED}❌ Usage: $0 <source_folder> <remote_url>${RESET}"
    exit 1
fi

if [ ! -d "$SRC_FOLDER" ]; then
	$SECHO "${RED}❌ Source folder '$SRC_FOLDER' does not exist.${RESET}"
    exit 1
fi

TMP_DIR=$(mktemp -d)
cp -r "$SRC_FOLDER"/. "$TMP_DIR"/

cd "$TMP_DIR" || { $SECHO "${RED}❌ Failed to change directory to '$TMP_DIR'.${RESET}"; exit 1; }

git init > /dev/null
git remote add vogs "$REMOTE_URL"
git checkout -b master

git add .
git commit -m "Clean push for school" -m "This is an automatic commmit from the push_vog script."> /dev/null
git push vogs master --force

cd - > /dev/null
rm -rf "$TMP_DIR"

$SECHO "${GREEN}✔ Successfully pushed to VOG.${RESET}"
