/* Generated by theme/apply-theme.sh — edit theme/colors.sh instead */

* {
	border: none;
	border-radius: 0;
	min-height: 0;
	font-family: "SF Pro Display", "Inter", "JetBrainsMono Nerd Font", sans-serif;
	font-size: 16px;
	min-height: 0;
	padding: 0;
	margin: 0;
}

.modules-center {
	background: {{bg1_90}};
	padding: 6px 12px;
	margin: 0 0 15px 0;
	border-radius: 28px;
	box-shadow: 0 4px 12px {{shadow_20}};
}

window#waybar {
	background: transparent;
}

tooltip {
	background: {{bg0_96}};
	border: 1px solid {{bg3_90}};
	border-radius: 12px;
}

tooltip label {
	color: {{fg}};
	padding: 6px;
}

#workspaces {
	background: transparent;
	padding: 0;
	margin: 0 10px 0 10px;
	border: none;
	box-shadow: none;
}

#workspaces button {
	padding: 0 6px;
	margin: 0 2px;
	border-radius: 16px;
	color: {{fg1_50}};
	background: transparent;
	transition: color 0.3s ease-in-out;
}

#workspaces button.active {
	background: linear-gradient(135deg, {{blue_90}}, {{purple_90}}, {{pink_90}});
	color: {{fg}};
	min-width: 40px;
	transition: all 0.3s ease-in-out;
}

#workspaces button:hover {
	background-color: {{hover_20}};
	color: {{fg1_90}};
}

#workspaces button.urgent {
	background-color: {{red}};
	color: {{fg}};
}

#clock {
	color: {{fg0}};
	font-weight: 600;
	padding: 0 10px;
}


#wireplumber {
	color: {{yellow_85}};
	padding: 0 10px;
}

#wireplumber.muted {
	color: {{yellow_30}};
}

#network {
	color: {{purple_85}};
	padding: 0 10px;
}

#network.disconnected {
	color: {{purple_30}};
}

#battery {
	color: {{green_85}};
	padding: 0 10px;
}

#battery.warning { color: {{orange_90}}; }
#battery.critical { color: {{rose_90}}; }
#battery.charging { color: {{green_90}}; }
