$active_border = 0xff{color4}
$inactive_border = 0xff{color0}
$shadow_color = 0xaa{color0}
$blue   = 0xff{color4}
$purple = 0xff{color5}
$green  = 0xff{color2}
$red    = 0xff{color1}
$yellow = 0xff{color3}
$aqua   = 0xff{color6}
$bg0    = 0xff{color0}
$bg2    = 0xff{color8}
$fg     = 0xff{foreground}
