# Generated by theme/apply-theme.sh — edit theme/colors.sh instead

[global]
    font = SF Pro Display 11
    markup = full
    format = "<b>%s</b>\n%b"
    sort = yes
    indicate_hidden = yes
    alignment = left
    show_age_threshold = 60
    word_wrap = yes
    ignore_newline = no
    idle_threshold = 120
    monitor = 0
    follow = mouse
    sticky_history = yes
    history_length = 20
    show_indicators = no
    line_height = 2
    separator_height = 1
    padding = 12
    horizontal_padding = 16
    separator_color = "{{bg3_hex40}}"
    frame_width = 1
    frame_color = "{{bg3}}"
    corner_radius = 8
    background = "{{bg0}}"
    foreground = "{{fg}}"
    offset = 12x12
    origin = top-right

[urgency_low]
    background = "{{bg0}}"
    foreground = "{{fg2}}"
    timeout = 5

[urgency_normal]
    background = "{{bg0}}"
    foreground = "{{fg}}"
    timeout = 8

[urgency_critical]
    background = "{{bg0}}"
    foreground = "{{fg}}"
    frame_color = "{{bg4}}"
    timeout = 0
