# Generated by theme/apply-theme.sh — edit theme/colors.sh instead

font=Cozette 11
format=<b>%a ⏵</b> %s\n%b
sort=-time
output=DP-2
layer=overlay
anchor=top-right
background-color={{mako_bg}}
width=300
height=110
margin=5
padding=0,5,10
border-size=2
border-color={{mako_border}}
border-radius=15
icons=0
max-icon-size=64
default-timeout=5000
ignore-timeout=1

[urgency=low]
border-color={{mako_low}}
background-color={{mako_low}}

[urgency=normal]
border-color={{mako_normal}}
background-color={{mako_normal}}

[urgency=high]
border-color={{mako_critical}}
background-color={{mako_critical}}
default-timeout=10000

[app-name=lightcord]
border-color={{mako_border}}

[summary~="log-.*"]
border-color={{mako_low}}

[app-name=lightcord summary~="(.*(^| )orz|ORZ|sto|STO|otl|OTL( |$).*)"]
invisible=1
