#!/bin/bash

if [ -z "$1" ]; then
    echo "Usage: $0 <soundcloud_playlist_url> [output_folder_name]"
    exit 1
fi

PLAYLIST_URL="$1"
BASE_OUTPUT_DIR="$HOME/Downloads/soundcloud_playlist"

if [ -n "$2" ]; then
    OUTPUT_DIR="$BASE_OUTPUT_DIR/$2"
else
    OUTPUT_DIR="$BASE_OUTPUT_DIR/default"
fi
mkdir -p "$OUTPUT_DIR"

yt-dlp --extract-audio --audio-format mp3 --output "$OUTPUT_DIR/%(title)s.%(ext)s" "$PLAYLIST_URL"
