#!/bin/bash

if [ -z "$1" ]; then
    echo "Usage: $0 <youtube-url>"
    exit 1
fi

URL=$(echo "$1" | cut -d'&' -f1)

yt-dlp \
  -x --audio-format mp3 \
  --embed-thumbnail \
  --add-metadata \
  -o "%(title)s.%(ext)s" \
  "$URL"
