#!/bin/bash

repos=(
  "$HOME/.dotfiles"
  "$HOME/lab/libft"
  "$HOME/lab/ft_printf"
  "$HOME/lab/get_next_line"
  "$HOME/lab/MiniTalk"
)

all_clean=true

for repo in "${repos[@]}"; do
  repo_name=$(basename "$repo")

  if [ ! -d "$repo/.git" ]; then
    echo "$repo_name: ❌ Not a git repository."
    all_clean=false
    continue
  fi

  cd "$repo" || continue
  git fetch &> /dev/null

  status_line=$(git status -sb 2>/dev/null | head -n 1)
  uncommitted=$(git status --porcelain)

  if [ -n "$uncommitted" ]; then
    notify-send -u normal "$repo_name" "✏️ You have uncommitted changes."
	  all_clean=false
	elif [[ "$status_line" == *"[ahead "* ]]; then
	  notify-send -u normal "$repo_name" "🔼 You have commits to push."
	  all_clean=false
	elif [[ "$status_line" == *"[behind "* ]]; then
	  notify-send -u normal "$repo_name" "🔽 There are commits to pull."
	  all_clean=false
	elif [[ "$status_line" == *"[diverged"* ]]; then
	  notify-send -u critical "$repo_name" "⚠️ Branch has diverged."
	  all_clean=false
  fi
done

if $all_clean; then
  notify-send -u normal "Git Push Check" "✅ All repositories are up-to-date."
fi

