#!/bin/bash

TASK_DIR="$HOME/.dotfiles/scripts/tasks/tasks_json"

mkdir -p "$TASK_DIR"

if [ -z "$1" ]; then
    echo "Please provide a task description."
    exit 1
fi

DESCRIPTION="$*"
DATE=$(date '+%Y-%m-%d %H:%M:%S')

# Trouver dernier ID
LAST_ID=0
for file in "$TASK_DIR"/*.json; do
    [[ -e "$file" ]] || break
    id=$(basename "$file" .json)
    if (( id > LAST_ID )); then
        LAST_ID=$id
    fi
done

NEW_ID=$((LAST_ID + 1))
TASK_FILE="$TASK_DIR/$NEW_ID.json"

jq -n --arg id "$NEW_ID" --arg status "todo" --arg date "$DATE" --arg desc "$DESCRIPTION" \
    '{id: ($id|tonumber), status: $status, date: $date, description: $desc}' > "$TASK_FILE"

echo "Task added with ID $NEW_ID."
