#!/bin/bash

TASK_DIR="$HOME/.dotfiles/scripts/tasks/tasks_json"
GIT_REPO="$HOME/.dotfiles"

SLOW_ECHO="$HOME/.dotfiles/scripts/utils/slow_echo"
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
RESET='\033[0m'

if [ -z "$1" ]; then
	echo -e "${RED}"
    $SLOW_ECHO "Please provide a task ID."
	echo -e "${RESET}"
    exit 1
fi

ID="$1"
TASK_FILE="$TASK_DIR/$ID.json"

if [ ! -f "$TASK_FILE" ]; then
	echo -e "${RED}"
    $SLOW_ECHO "Task $ID not found."
	echo -e "${RESET}"
    exit 1
fi

jq '.status = "done"' "$TASK_FILE" > "$TASK_FILE.tmp" && mv "$TASK_FILE.tmp" "$TASK_FILE"

echo -e "${GREEN}"
$SLOW_ECHO "Task $ID marked as done."
echo -e "${RESET}"

git -C "$GIT_REPO" add "$TASK_FILE" > /dev/null 2>&1
MSG="Automatic tasks: Marked $ID as done"
git -C "$GIT_REPO" commit -m "$MSG" > /dev/null 2>&1
git -C "$GIT_REPO" push origin main > /dev/null 2>&1
echo -e "${YELLOW}"
$SLOW_ECHO "Task pushed to git: '$MSG'"
echo -e "${RESET}"
