#!/bin/bash

TASK_DIR="$HOME/.dotfiles/scripts/tasks/tasks_json"
GIT_REPO="$HOME/.dotfiles"

if [ -z "$1" ]; then
    echo "Please provide a task ID."
    exit 1
fi

ID="$1"
TASK_FILE="$TASK_DIR/$ID.json"

if [ ! -f "$TASK_FILE" ]; then
    echo "Task $ID not found."
    exit 1
fi

jq '.status = "done"' "$TASK_FILE" > "$TASK_FILE.tmp" && mv "$TASK_FILE.tmp" "$TASK_FILE"

echo "Task $ID marked as done."

git -C "$GIT_REPO" add "$TASK_FILE"
MSG="Automatic tasks: Marked $ID: $DESCRIPTION"
git -C "$GIT_REPO" commit -m "$MSG"
git -C "$GIT_REPO" push origin main
echo "Task pushed to git: $MSG"
