#!/bin/bash

TASK_FILE="$HOME/.dotfiles/scripts/tasks/tasks.txt"

# Couleurs ANSI
RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m'  # No Color

if [ ! -f "$TASK_FILE" ]; then
    echo "No tasks found."
    exit 0
fi

echo -e "ID\tStatus\t\tDate\t\t\tDescription"
echo "-----------------------------------------------------------------"

while IFS=';' read -r id status date desc; do
    if [ "$status" != "todo" ]; then
        continue
    fi

    status_colored="${RED}${status}${NC}"

    printf "%-3s\t%-8b\t%-19s\t%s\n" "$id" "$status_colored" "$date" "$desc"
done < "$TASK_FILE"

