#!/bin/bash

TASK_DIR="$HOME/.dotfiles/scripts/tasks/tasks_json"

RED='\033[0;31m'
NC='\033[0m'

SLOW_ECHO="$HOME/.dotfiles/scripts/utils/slow_echo"
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
RESET='\033[0m'

if [ ! -d "$TASK_DIR" ] || [ -z "$(ls -A $TASK_DIR)" ]; then
    $SLOW_ECHO "${RED}No tasks found.${RESET}"
    exit 0
fi

$SLOW_ECHO "ID\tStatus\t\tDate\t\t\tDescription"
echo "-----------------------------------------------------------------"

for file in "$TASK_DIR"/*.json; do
    status=$(jq -r '.status' "$file")
    if [ "$status" != "todo" ]; then
        continue
    fi

    id=$(jq '.id' "$file")
    date=$(jq -r '.date' "$file")
    desc=$(jq -r '.description' "$file")

    status_colored="${RED}${status}${NC}"

    line="$(printf "%-3s\t%-25s\t%-19s\t%s" "$id" "$status_colored" "$date" "$desc")"
	$SLOW_ECHO "$(echo -e "$line")"
done
