#!/bin/bash

TASK_DIR="$HOME/.dotfiles/scripts/tasks/tasks_json"

if [ ! -d "$TASK_DIR" ] || [ -z "$(ls -A $TASK_DIR)" ]; then
    echo "No tasks found."
    exit 0
fi

echo -e "ID\tStatus\t\tDate\t\t\tDescription"
echo "-----------------------------------------------------------------"

for file in "$TASK_DIR"/*.json; do
    id=$(jq '.id' "$file")
    status=$(jq -r '.status' "$file")
    date=$(jq -r '.date' "$file")
    desc=$(jq -r '.description' "$file")

    # Colore status
    if [ "$status" = "todo" ]; then
        status_colored="\033[0;31m$status\033[0m"
    elif [ "$status" = "done" ]; then
        status_colored="\033[0;32m$status\033[0m"
    else
        status_colored="$status"
    fi

    printf "%-3s\t%-8b\t%-19s\t%s\n" "$id" "$status_colored" "$date" "$desc"
done
