#!/bin/bash

TASK_DIR="$HOME/.dotfiles/scripts/tasks/tasks_json"

RED='\033[0;31m'
NC='\033[0m'

if [ ! -d "$TASK_DIR" ] || [ -z "$(ls -A $TASK_DIR)" ]; then
    echo "No tasks found."
    exit 0
fi

echo -e "ID\tStatus\t\tDate\t\t\tDescription"
echo "-----------------------------------------------------------------"

for file in "$TASK_DIR"/*.json; do
    status=$(jq -r '.status' "$file")
    if [ "$status" != "todo" ]; then
        continue
    fi

    id=$(jq '.id' "$file")
    date=$(jq -r '.date' "$file")
    desc=$(jq -r '.description' "$file")

    status_colored="${RED}${status}${NC}"

    printf "%-3s\t%-8b\t%-19s\t%s\n" "$id" "$status_colored" "$date" "$desc"
done
