#!/bin/bash

TASK_DIR="$HOME/.dotfiles/scripts/tasks/tasks_json"

SLOW_ECHO="$HOME/.dotfiles/scripts/utils/slow_echo"
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
RESET='\033[0m'

if [ ! -d "$TASK_DIR" ] || [ -z "$(ls -A $TASK_DIR)" ]; then
	echo -e "${RED}"
    $SLOW_ECHO "No tasks found."
	echo -e "${RESET}"
    exit 0
fi

$SLOW_ECHO "ID\tStatus\t\tDate\t\t\tDescription"

$SLOW_ECHO "-----------------------------------------------------------------"

for file in "$TASK_DIR"/*.json; do
    id=$(jq '.id' "$file")
    status=$(jq -r '.status' "$file")
    date=$(jq -r '.date' "$file")
    desc=$(jq -r '.description' "$file")

    # Colore status
    if [ "$status" = "todo" ]; then
        status_colored="\033[0;31m$status\033[0m"
    elif [ "$status" = "done" ]; then
        status_colored="\033[0;32m$status\033[0m"
    else
        status_colored="$status"
    fi

    line="$(printf "%-3s\t%-25s\t%-19s\t%s" "$id" "$status_colored" "$date" "$desc")"
    $SLOW_ECHO "$(echo -e "$line")"
done
