#!/bin/bash

SCRIPT_DIR="$HOME/.dotfiles/scripts/tasks"

if [ ! -d "$SCRIPT_DIR" ]; then
	echo "Script directory not found: $SCRIPT_DIR"
	exit 1
fi

case "$1" in
	-a|add)
		shift
		$SCRIPT_DIR/add_task "$@"
		;;
	-m|mark)
		shift
		$SCRIPT_DIR/mark_task "$@"
		;;
	-d|delete)
		shift
		$SCRIPT_DIR/remove_task "$@"
		;;
	-s|show)
		$SCRIPT_DIR/show_all_tasks
		;;
	-su|show_undone)
		$SCRIPT_DIR/show_undone_tasks
		;;
	-v|vim)
		$SCRIPT_DIR/vim_the_task "$@"
		;;
	*)
		echo "Usage: $0 {-a|add|-m|mark|-d|delete|remove|-s|show|-su|show-undone} [args]"
		;;
esac

