/* Generated by theme/apply-theme.sh — edit theme/colors.sh instead */
/* ROUNDED THEME FOR ROFI */
/* Author: Newman Sanchez (https://github.com/newmanls) */

* {
    bg0:    {{rofi_bg0}};
    bg1:    {{rofi_bg1}};
    bg2:    {{rofi_bg2}};
    bg3:    {{rofi_bg3}};
    fg0:    {{rofi_fg0}};
    fg1:    {{rofi_fg1}};
    fg2:    {{rofi_fg2}};
    fg3:    {{rofi_fg3}};
}

@import "template/rounded-template.rasi"
